### ISSUE TITLE
die in t/http-client.t and t/http-log-file.t give confusing output

### ISSUE THREAD

**Issue by sjn** [croservices/cro-http#1]
Hey guys, nice work with Cro! :D 

So, this is how a successful test run looks.

===========8<----------------
$ cd cro-http
$ zef test .
===> Testing: Cro::HTTP:ver('0.7')
Sudden error
  in block  at t/http-client.t line 71
  in code  at /home/sjn/src/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 79

No more
  in block  at t/http-log-file.t line 19
  in code  at /home/sjn/src/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 79

===> Testing [OK] for Cro::HTTP:ver('0.7')
------------------------>8===============

It looks like something went wrong, but nothing did.

Would it be possible to make the output look less "error-y"? At the moment, it's an attention-waster for newbies like myself. :)

**Comment by Altai-man** [comment]
Well, I was thinking about it too, thanks for noting!

The situation is a bit design-wise vs testing-wise... If an exception is thrown, we "wrap it up" with a simple 500 response, but test-wise we can imitate that without explicit `die`, I think.

Fixed with latest commit.
