### ISSUE TITLE
Blocking Put request with 'stream in half-closed(remote)' message

### ISSUE THREAD

**Issue by wbiker** [croservices/cro-http#118]
I encountered an issue when using Cro::HTTP::Client to upload a tar archive to OBS.
Every time I try to upload the DBIish sources to https://build.opensuse.org/project/show/home:wbiker/perl6-DBIish the upload precess stops until the program is aborted with ctrl+c.
CRO_TRACE=1 reveals:

`
[TRACE(anon 3)] Cro::ConnectionConditional EMIT TCP Message
  00 00 00 00 01 00 00 00 01                       .........

[TRACE(anon 3)] Cro::TLS::Connector EMIT TCP Message
  00 00 2b 07 00 00 00 00 00 00 00 00 01 00 00 00  ..+.............
  05 44 41 54 41 3a 20 73 74 72 65 61 6d 20 69 6e  .DATA: stream in
  20 68 61 6c 66 2d 63 6c 6f 73 65 64 28 72 65 6d   half-closed(rem
  6f 74 65 29                                      ote)

[TRACE(anon 3)] Cro::TLS::Connector DONE
[TRACE(anon 2)] Cro::TLS::Connector EMIT TCP Message
  00 00 0f 07 00 00 00 00 00 00 00 00 01 00 00 00  ................
  00 74 69 6d 65 6f 75 74                          .timeout

[TRACE(anon 2)] Cro::TLS::Connector DONE
`

The upload works. The data are uploaded and listed in frontend. But according to the output, the stream is half closed and either side waits for an FIN.

Attached is the tar file I used here. Note, I had to rename the file to end with .zip otherwise github does not upload a tar.xz file. Just remove the .zip extension.

The code in question looks like this:
`my $c = Cro::HTTP::Client.new(auth => { username => "username", password => "password" });
my $tar-archive-binary-content = $tar-path.slurp(:bin, :close);
$!client.put($url-source-archive, content-type => "application/octet-stream", body => $tar-archive-binary-content);
`

**Comment by patrickbkr** [comment]
I'm hitting the exact same error also trying to upload files to OBS. The reason is, that Cro doesn't support tracking the remote end HTTP2 window sizes. This causes a connection abort as soon as the remote window size overflows. This can either happen when uploading a larger file as a client or when sending a larger file to a client. Usually more data than the typical default window size of 65kb suffices to flood the remote and cause an abort.
I'm looking into fixing this.

**Comment by patrickbkr** [comment]
The PR has been merged more than a year ago. I believe this is fixed. @wbiker Do you want to verify, or can we just close this?

**Comment by wbiker** [comment]
@patrickbkr Hallo Patrick!
Just uploaded DBIish to OBS without an issue! Thanks for fixing and thanks for your work for Raku!
