### ISSUE TITLE
:%ca parameter for Cro::HTTP::Client is not documented

### ISSUE THREAD

**Issue by Antisunny** [croservices/cro-http#119]
Im fetching a page using `Cro::HTTP::Client`, how can I specify a certfile `.cer`/ in a request?

**Comment by Antisunny** [comment]
found! 

https://github.com/croservices/cro-http/blob/master/lib/Cro/HTTP/Client.pm6

specify `ca` with the path to `.cer` file.

**Comment by Altai-man** [comment]
Thanks for your report!
The `ca` parameter should be documented at https://cro.services/docs/reference/cro-http-client
I will re-make the issue~

**Comment by Antisunny** [comment]
Still not figured out which is right.

```raku
my $client = Cro::HTTP::Client.new:
    ca => {
        certificate-file => '/path/to/cer/file',
        
    }
```
OR
```raku
    ca => {
        ca-file => '/path/to/cer/file',
    }
```

**Comment by Altai-man** [comment]
The second one is correct. You can find it in tests (e.g. https://github.com/croservices/cro-tls/blob/master/t/tls.t#L8-L12). (but of course it should be properly documented instead of "go see tests")

**Comment by jnthn** [comment]
I documented it yesterday in https://github.com/croservices/cro/commit/73fd2832b177e4a3ca960fbb41ddfe6684dbf60e.
