### ISSUE TITLE
Implement `Capture` method in WWWFormUrlEncoded and Multipart body objects

### ISSUE THREAD

**Issue by jnthn** [croservices/cro-http#13]
The docs speculate that you should be able to do destructuring of a request body:

```
post -> 'product' {
    request-body -> (:$name!, :$description!, :$price!) {
        # Do stuff here...
    }
}
```

And indeed that should work well with JSON (I think we have a test, but it'd be wise to check). It won't, however, work yet with forms posted from the browser, which is a pity.

Thankfully, an object can choose how it destructures, so we can implement this. I'd implement #12 first. And then we can just have `method Capture() { Capture.new(hash => self.hashed) }` or some such. Plus some tests to make sure it works out.

**Comment by Altai-man** [comment]
See https://github.com/croservices/cro-http/issues/12#issuecomment-331094460
