### ISSUE TITLE
Support for HTTP PATCH

### ISSUE THREAD

**Issue by jnthn** [croservices/cro-http#15]
The [documentation](http://cro.services/docs/reference/cro-http-router#URI_segment_matching) indicates that there is a `patch` function that handles the `PATCH` HTTP method, but we didn't yet implement it. Let's add that, as well as adding it [here](https://github.com/croservices/cro-http/blob/master/lib/Cro/HTTP/RequestParser.pm6#L12) and also adding support in `Cro::HTTP::Client`. Plus let's update the docs for `Cro::HTTP::Client` to mentioned that.

**Comment by Altai-man** [comment]
Should be good with https://github.com/croservices/cro-http/commit/5e7ab25ba7ed155e17665055f6c6906e2194bd71, https://github.com/croservices/cro/commit/88a786ec75ee39c2005f6cb26bdf51da2134b051 and https://github.com/croservices/cro/commit/00430b90fc705e0b49bdd3f797704eb7b500beff.
Re-open if something is missing.
