### ISSUE TITLE
Native call expected argument 2 to reference a native integer, but got NativeRef

### ISSUE THREAD

**Issue by demanuel** [croservices/cro-http#170]
I have my client:
 
` my $!api-client = Cro::HTTP::Client.new(headers => [], cookie-jar => Any, body-serializers => Any, add-body-serializers => Any, body-parsers => Any, add-body-parsers => Any, content-type => Any, follow => 5, http => Any, ca => ${:insecure(Bool::True)}, base-uri => Cro::Uri.new(scheme => "https", authority => "my.url.com", userinfo => Str, host => "my.url.com", host-class => Cro::ResourceIdentifier::Host::RegName, port => 46055, path => "/api/latest/", query => Str, fragment => Str), push-promises => Bool::False, user-agent => "Cro", auth => {:password("admin"), :username("admin")}, http-proxy => Cro::Uri, https-proxy => Cro::Uri, timeout-policy => Cro::Policy::Timeout)`
 and  i'm doing:
 
` await $!api-client.get($endpoint, query=>{messageId=>99999});`
 
 This code is simpy dying with the error 
`Native call expected argument 2 to reference a native integer, but got NativeRef`

using `CRO_TRADE=1` doesn't show anything.

The following curl call works fine:
`curl --insecure -X GET "https://admin:admin@my.url.com:46055/api/latest/my.end.point?messageId=99999"`

Versions:

 Cro: 0.8.7

Welcome to Rakudo™ v2021.12-200-gfefbc725f.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12-136-gef95f0031.

**Comment by demanuel** [comment]
Found a workaround.

If i define the http version to version 1.1, the issue doesn't happen.

**Comment by jnthn** [comment]
There were some Rakudo changes that causes regressions in a couple of dependencies; this module and `Cro::TLS` have been patched to set a minimum version of `IO::Socket::Async::SSL` and `HTTP::HPACK` (you can install latest of those manually until the next Cro release, which is planned for later this month).
