### ISSUE TITLE
`static` accepts Strs and denies IOs, only to turn Str into an IO later on

### ISSUE THREAD

**Issue by AlexDaniel** [croservices/cro-http#21]
https://github.com/croservices/cro-http/blob/8084e8e209c95fd61bd431cb88b3b0f0f67263af/lib/Cro/HTTP/Router.pm6#L942-L971

Perhaps it should be `IO() $base`?

**Comment by jnthn** [comment]
Yeah, agree. Also, somebody was recently inconvenienced by this being `@path?` rather than `*@path`, so probably worth changing that at the same time.

**Comment by Altai-man** [comment]
Closed with https://github.com/croservices/cro-http/commit/49c656d692b46aaaa4c62f0b6847c5da3cb89d86.
