### ISSUE TITLE
Make it easier to work with extra HTTP methods

### ISSUE THREAD

**Issue by jnthn** [croservices/cro-http#23]
See [this workaround](https://gist.github.com/FROGGS/8c583a250f175a18f56580aac3c8e46d) and provide a better way.

**Comment by Altai-man** [comment]
https://github.com/croservices/cro-http/pull/35 should fix that.

**Comment by jnthn** [comment]
Functionality added, I'll close this once I've written the docs.

**Comment by jnthn** [comment]
Documented the HTTP server, router, and client aspects of working with the not-so-common request methods, so I think we're good now. Hope this'll make things easier for you, @FROGGS (release coming in next day or two).
