### ISSUE TITLE
Change default ciphers

### ISSUE THREAD

**Issue by lancew** [croservices/cro-http#25]
Having deployed a cro site, I found that the SSLLabs score for the site was negatively affected by the default cipher set in cro-http.

I solved on my site by setting the cipher set manually in service.p6

I have a potential pull request to make the mozilla recommendations the default here: https://github.com/lancew/cro-http/commit/f7c6e4ca48c75983f959e395b541019701b29cd4

Raising an issue before pull request as I have not yet run tests and wanted to get opinions before pushing a pull request.

Lance

**Comment by jnthn** [comment]
Yes, this seems like a good thing to do.

**Comment by lancew** [comment]
Pull request made: https://github.com/croservices/cro-http/pull/26

**Comment by jnthn** [comment]
Merged, thank you!
