### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by GildedHonour** [croservices/cro-http#30]
```
zef install --/test cro
===> Searching for: cro
No candidates found matching identity: cro

```

**Comment by jnthn** [comment]
I'm guessing it must be some kind of transient failure, or maybe regression somewhere in Rakudo or zef if you're running very recent commits of those.

That exact command has been on the Cro homepage for the better part of a year, and must have been run thousands of times. I just tried copying the command here and running it in a Rakudo Star docker container (for the sake of clean environment and to make sure it isn't a typo), and it found it just fine and started installing it also.

Could try `zef update`, just in case, though I thought zef was good at doing that automatically.

**Comment by GildedHonour** [comment]
Yeah, found now.
Is there an example of a simple web app which renders an html page?

**Comment by GildedHonour** [comment]
Found it too.
