### ISSUE TITLE
Adding cookes directly to Cro::HTTP::Client::CookieJar

### ISSUE THREAD

**Issue by Xliff** [croservices/cro-http#37]
Can someone explain to me why this would be a bad thing to do? If not, would you accept a PR to basically do:

```
push @!cookies: $newCookie
```

**Comment by Xliff** [comment]
Submitted #39 for discussion. Thanks!

**Comment by jnthn** [comment]
The PR was merged, and I just added documentation in https://github.com/croservices/cro/commit/11000d5716ff834f83b9c94943418ea8e593414d.
