### ISSUE TITLE
Request objects not available via it's associated Response object

### ISSUE THREAD

**Issue by Xliff** [croservices/cro-http#38]
Whenever I try to access the headers used in a response, I try using the following code:

```perl6
$resp.request.headers().gist.say
```
I get the following error:

```
Cannot look up attributes in a Cro::HTTP::Request type object
in method headers at /home/cbwood/Projects/rakudobrew/moar-master/install/share/perl6/site/sources/92FAFA2680EF5E9D02868F366DD1A69EC6268609 (Cro::HTTP::Message) line 10
```
Is the request object not getting passed back when the response is created?

**Comment by Altai-man** [comment]
It should be passed back, so bug.

Can you try to reproduce it in a small gist(with `routes` block if you are using it or another way), so we could investigate and fix?

**Comment by jnthn** [comment]
@Altai-man Missing info (this was just discussed on IRC): this happens with the client.

**Comment by Altai-man** [comment]
@jnthn I guess you can assign me for some fix/tests.
