### ISSUE TITLE
Include request object in response-type exceptions

### ISSUE THREAD

**Issue by Altreus** [croservices/cro-http#41]
If there is an error in a request that causes an exception, it would be very helpful if the request that caused it were also available in the exception object.

**Comment by Altai-man** [comment]
cast @jnthn.
I can fix that in a couple of lines, should we? Looks like a useful feature.

**Comment by jnthn** [comment]
Depends on https://github.com/croservices/cro-http/issues/38

**Comment by Altreus** [comment]
When I tried getting the request from the response in the exception it said it was not defined.

I think this might help.

```
--- a/lib/Cro/HTTP/Client.pm6
+++ b/lib/Cro/HTTP/Client.pm6
@@ -418,6 +418,7 @@ class Cro::HTTP::Client {
                                 .emit;
                             };
                         } else {
+                            .request = $request-object;
                             die X::Cro::HTTP::Error::Client.new(response => $_);
                         }
                     } elsif .status >= 500 {
```

**Comment by jnthn** [comment]
@Altai-man With #38 merged, is this now resolved?

**Comment by jnthn** [comment]
Ah, actually maybe should document it too.

**Comment by Altai-man** [comment]
@jnthn it is now resolved, but yes, we should document it too.

**Comment by jnthn** [comment]
Documentation added in https://github.com/croservices/cro/commit/fed6f8eed2.
