### ISSUE TITLE
Cro::HTTP::Auth::WebToken::Bearer using the wrong header

### ISSUE THREAD

**Issue by Scimon** [croservices/cro-http#48]
Cro::HTTP::Auth::WebToken::Bearer is using the "Auth" header rather than the "Authorization" header. Is there a reason for this?

**Comment by Scimon** [comment]
Cool. Sorry for the terse issue. I'd just spent a while trying to work out why it wasn't working and was a bit tired.

I've patched my local Auth class for now. Onwards and upwards.

**Comment by Altai-man** [comment]
No problem. Thanks for your patience, catching various sorts of bugs is always a hard task.
Latest commit fixes the issue, I believe. Sorry for such an issue from me.
