### ISSUE TITLE
We appear to be sending `Accept-Encoding: gzip` even though we don't support it

### ISSUE THREAD

**Issue by Altreus** [croservices/cro-http#53]
From this line:
https://github.com/shuppet/p6-api-discord/blob/getting-stuff/lib/API/Discord/User.pm6#L40

Via this line:
https://github.com/shuppet/p6-api-discord/blob/getting-stuff/lib/API/Discord/HTTPResource.pm6#L55

We get `Accept-Encoding: gzip`:
https://gist.github.com/Altreus/da26124597b0c8795ff7b858b925adad

**Comment by jnthn** [comment]
It seems like [the module is adding that header](https://github.com/shuppet/p6-api-discord/blob/c8cde5486201895e39cfc3df6f4820b80c0ea668/lib/API/Discord/Connection.pm6#L81).

**Comment by jnthn** [comment]
And the `keep-alive` will also be sent automatically.

**Comment by Altreus** [comment]
Confirmed - PEBKAC error

I forgot I cargo-culted the headers from a working library way back when I started all this

Sorry!
