### ISSUE TITLE
Cookie Restrictions

### ISSUE THREAD

**Issue by rbt** [croservices/cro-http#54]
I have a cookie set by other programs (javascript actually) which I want to import via Cro.

I find myself doing this:

```
		get -> 'something', :$JSON! is cookie 
		{
			my $decoded = decode-percents($JSON);
			my %session = from-json($decoded);
		}
```

I grabbed decode-percents from Cro::URI.

Cro::HTTP::Cookie currently restricts CookieValue to a certain set of values instead of encoding/decoding it the same as is done with URI segments.

**Comment by jnthn** [comment]
I remember researching this back when designing it that way. Looking at [the RFC](https://tools.ietf.org/html/rfc6265.html) again, I think this is problematic part:

>  The semantics of the cookie-value are not defined by this document.
> 
>   To maximize compatibility with user agents, servers that wish to
>   store arbitrary data in a cookie-value SHOULD encode that data, for
>   example, using Base64 [RFC4648].

That is to say, it doesn't actually specify a standardized way to encode a cookie. In fact, the one it mentions as an example - Base64 - is not the one you're wanting. Thus, the design at present is to make it very clear that, should one wish to store something that needs encoding in a cookie, then the encoding scheme must be picked.

We might be able to get some configurable mechanism in there to save every route handler repeatedly solving the problem, however.
