### ISSUE TITLE
Large binary files cause "operation canceled"

### ISSUE THREAD

**Issue by rbt** [croservices/cro-http#55]
Sending content over a couple MB causes "operation canceled". The amount of data shipped seems to vary from run to run so I expect some buffer is filling up. Of course, I'm not exactly sure where it happens as I'm not getting a backtrace and "operation canceled" doesn't exist in the cro source.

This is on the croservices/cro-http:0.7.6 container within kubernetes 1.10.5.

```
use Cro::HTTP::Router;

sub routes() is export {
    route {
	    get -> 'sample.txt' {
	        content 'text/plain', 'A' x 10_000_000;
	    }
	}
}
```

I found the problem with binary data (images) but it seems to happen with text too.

**Comment by jnthn** [comment]
The error text "operation cancelled" appears in the libuv source, which is used for async I/O in MoarVM; it's the text that goes with an `ECANCELED`, which comes back from some system call. Will have a look at reproducing.

**Comment by jnthn** [comment]
Couldn't reproduce it on Linux (Ubuntu 16.04) outside of a container; maybe that'll turn out to be the significant part.

**Comment by rbt** [comment]
I looked at this a bit more. I do most of my testing via the minikube with nearly the entire stack and seems I just happened on the 1 way it breaks. Per5 (Plack/Twiggy) with a similar configuration works fine.

Running on my local machine outside of minikube works fine.

Added wget to the container and tried pulling via localhost. This works fine.

Via the NodePort service also works perfectly fine.

I installed the container into Google Cloud with a global load balancer infront (SSL) and it also works fine.


So I guess it's just minikube through the ingress which is an nginx reverse proxy (minikube defaults, including SSL). The ingress logs don't offer much except blaming perl6 for the disconnect:

> {"log":"2018/10/21 14:44:15 [error] 1922#1922: *641737 upstream prematurely closed connection while reading upstream, client: 192.168.39.1, server: _, request: \"GET /sample.txt HTTP/2.0\", upstream: \"http://172.17.0.14:81/sample.txt\", host: \"www.local\"\n","stream":"stderr","time":"2018-10-21T14:44:15.068427389Z"}
> {"log":"192.168.39.1 - [192.168.39.1] - - [21/Oct/2018:14:44:15 +0000] \"GET /sample.txt HTTP/2.0\" 200 8992 \"-\" \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0\" 26 0.238 [bleed-fileserver-81] 172.17.0.14:81 1531656 0.238 200 fab913b324cd5734deac4df53dbf930a\n","stream":"stdout","time":"2018-10-21T14:44:15.068554492Z"}


I also tried upgrading Rakudo by injecting the croservices/cro-http:0.7.6 Dockerfile into the top of mine (see below) and upgrading the relevant bits. This still fails via the minikube ingress.


It's probably some system specific timing issue.


```
FROM rakudo-star:2018.06
MAINTAINER Jonathan Worthington <jonathan@edument.se>

ARG cro_version=0.7.6

RUN apt-get update && \
    apt-get --yes --no-install-recommends install libssl1.0-dev && \
    rm -rf /var/lib/apt/lists/* && \
    zef install --verbose 'Cro::Core:ver<'$cro_version'>' && \
    zef install --verbose 'Cro::TLS:ver<'$cro_version'>' && \
    zef install --debug 'Cro::HTTP:ver<0.7.6.1>'


#FROM croservices/cro-http:0.7.6
...
```

```
root@fileserver-6f7bb8db5d-hdc6n:/# perl6 --version
This is Rakudo Star version 2018.06 built on MoarVM version 2018.06
implementing Perl 6.c.
```
