### ISSUE TITLE
$*REQUEST is not accessible in session middleware

### ISSUE THREAD

**Issue by Altai-man** [croservices/cro-http#57]
```
use Cro::HTTP::Router;
use Cro::HTTP::Server;
use Cro::HTTP::Auth::Basic;

class MyUser does Cro::HTTP::Auth {
    has $.username;
}

subset LoggedInUser of MyUser where { .username.defined }

class MyBasicAuth does Cro::HTTP::Auth::Basic[MyUser, "username"] {
    method authenticate(Str $user, Str $pass --> Bool) {
        say "authentication called";
        forbidden unless $user eq 'admin' && $pass eq 'secret';
        return $user eq 'admin' && $pass eq 'secret';
    }
}

sub routes()
{
    my %storage;
    route {
        before MyBasicAuth.new;
        post -> LoggedInUser $user, 'api' {
            request-body -> %json-object {
                my $uuid = 'fake';
                %storage{$uuid} = %json-object;
                content 'application/json', %json-object
            }
        }
    }
}

my Cro::Service $app = Cro::HTTP::Server.new:
    :host<localhost>, :port<10000>,
    application => routes;

$app.start;
react whenever signal(SIGINT) { $app.stop; exit }
```

and with `curl --fail -H "Content-Type: application/json" -d '{"string":"hi"}' http://admin:foo@localhost:10000/api` you will get:
```
Can only use 'content' inside of a request handler
  in sub set-status at /home/koto/Work/cro/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 846
  in sub forbidden at /home/koto/Work/cro/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 823
  in method authenticate at perl6.pl6 line 14
  in method process-auth at /home/koto/Work/cro/cro-http/lib/Cro/HTTP/Auth/Basic.pm6 (Cro::HTTP::Auth::Basic) line 26
```

so we need to pass $*REQUEST in `process` of Basic middleware.

I suspect this issue is the same for all authentication types we have, so those want a test too.

**Comment by jnthn** [comment]
The error mentioning `content` is rather bogus. The dynamic in question is something like `$*CRO-ROUTER-REQUEST` or some such. But it's not *meant* to be available to middleware in general. It's a `Cro::HTTP::Router` thing, while middleware may be applied at server level, with none of the router sugar. Generally, the design is such that people don't *have* to use `Cro::HTTP::Router` to use the rest of the Cro things, including middleware.

Calling `forbidden` in the `authenticate` method is not something that should work. The contract of that method is to return a boolean saying whether the thing is authenticated or not. There is no response object even existing yet. And I believe we already produce the appropriate HTTP code when authorization fails. If one *did* want to map the code into a 403, then doing it in an `after` middleware would be the appropriate thing.

So, the only bug I see here is that it says `content` in the error message.

**Comment by jnthn** [comment]
@ufobat Left an answer there, but the issue is unintentionally depending on semantics of the next Cro release, which are different from what's currently available. (Also, the semantics we'll have in 0.8.0 are the ones folks would more likely expect, which is why we've changed them.)

**Comment by ufobat** [comment]
Thank you very much @jnthn. You're example of writing the routes works perfectly.

Maybe my comment is a bit off topic to this issue:
Regarding my example of having `401` for missing authentication and `403` for wrong authentication I want to add that I actually dont need that behaviour, it was just an theoretical example. 

According to what I understood so far, the middleware is located between the HTTP/Server level and the `Cro::HTTP::Router` part, right? And therefore the features of the Router (like `failure`) are not available. Are the requests and responses available or are they also part of the Router? Because from a naive user point of view one could argue that for processing the `Authorization` header you actually need to have the request parsed. So with a parsed request you could also expect that you should be able to have influence to the response. Maybe this is more a plugin then a middleware?

**Comment by jnthn** [comment]
> According to what I understood so far, the middleware is located between the HTTP/Server level and the Cro::HTTP::Router part, right? And therefore the features of the Router (like failure) are not available. 

There's a [quite detailed document](https://cro.services/docs/reference/cro-http-middleware) on the topic, but in summary:

* Middleware written as a class is decoupled from the router, such that it can be mounted either at server level or `route`-block level. Thanks to things like `delegate`, you can actually have middleware applied *after* the router has done some amount of matching, and ahead of further matching by a nested router.
* The router does provide `before` and `after` convenience forms taking a block. Within these, the router functionality is available. They're easier to write, though less re-usable. (They also internally work using the class form too.)

You could in some ways see *everything* in Cro as being middleware, in so far as all the things - the request parser, the router, the response serializer - are just things that implement the `Cro::Transform` role. Writing middleware is just inserting something else into that pipeline. Of course, implementing that role by hand would be tedious, so `Cro::HTTP::Middleware` provides a bunch of roles for common middleware patterns that take out the tedium (and also deal with the case where you need to do something at both request and response time, thus really needing two insertions into the pipeline).

And on top of *those*, we provide a few additional roles, like the basic auth one. That's [just a piece of middleware](https://github.com/croservices/cro-http/blob/master/lib/Cro/HTTP/Auth/Basic.pm6), but it handles all the request processing and just has you write a single method to decide if a username or password is valid. I'd figure that's flexible enough for most use cases, but if it's not, just implement one of the more generic roles, which'll give you a `Supply` of requests to process.

**Comment by Altai-man** [comment]
>So, the only bug I see here is that it says content in the error message.

This was fixed and tested in https://github.com/croservices/cro-http/commit/2e44853f4000baf21999203283139db2b4caf1bd
Another issue with 403/401 codes is fixed too, so closing. Please, re-open if needed.
