### ISSUE TITLE
HTTP/2 trace seems to report HTTP/1.1 requests

### ISSUE THREAD

**Issue by Altreus** [croservices/cro-http#69]
We were looking into a separate issue and noticed that we got a POST request via HTTP/1.1 even when the client object was constructed with `http => 2`.

It seems most likely to be a tracer issue, according to sena_kun on IRC

    13:30:11	<sena_kun>	oh, this is probably just a mistake of tracer.
    13:30:29	<sena_kun>	`PRI * HTTP/2.0` is being sent.

**Comment by Altai-man** [comment]
The issue is at https://github.com/croservices/cro-http/blob/master/lib/Cro/HTTP/Request.pm6#L60
and `http-version` not being populated with a correct value.
