### ISSUE TITLE
CookieString isn't compatible with cookies that legacy tomcat generates

### ISSUE THREAD

**Issue by titsuki** [croservices/cro-http#70]
Hi,
I found that tomcat had a bug about cookie processing [0].
[CookieString](https://github.com/croservices/cro-http/blob/master/lib/Cro/HTTP/Cookie.pm6#L30-L44) cannot parse cookies that legacy tomcat (i.e., tomcat which contains a bug of [0]) generates.

The bug is as follows (c.f., [0]):
```
When I set a cookie named "cookie_name" with value "value" and path "/", the header that's generated by Tomcat 8.0.28 looks like:

    Set-Cookie: cookie_name=value; Path=/

With 8.5.11, it looks like:

    Set-Cookie: cookie_name=value;path=/

Note the missing space after the semicolon and the change from "Path" to "path".
```

CookieString is strictly based on RFC 6265 [1] and requires SP after semicolon, so it cannot accept the latter one (i.e., "Set-Cookie: cookie_name=value;path=/").

I don't have a concrete idea but I think Cro::HTTP should provide a way to process such little-bit violated cookies.

Cheers,

+ [0] https://bz.apache.org/bugzilla/show_bug.cgi?id=60876
+ [1] RFC 6265: https://tools.ietf.org/html/rfc6265#section-4.1.1

**Comment by jnthn** [comment]
Thanks for the report and analysis. I concluded we'll simply tolerate the missing space, so we're robust in the face of this kind of malformed responses.
