### ISSUE TITLE
Add support for setting query parameters in GET requests

### ISSUE THREAD

**Issue by 0racle** [croservices/cro-http#90]
Currently there is no support for accepting a Hash or List of Pairs and converting them to query parameters in the GET request.

**Example**

```perl-6
$client.get('http://localhost/endpoint', form => {foo => 1, bar => 'simple text param'});
# Sends a request to `http://localhost/endpoint?foo=1&bar=simple+text+param`
```

> Keyword may not be `form` It could be `param`, or `query` or something else.

**Comment by CurtTilmes** [comment]
You can do this with [URI::Template](https://github.com/jonathanstowe/URI-Template):

```raku
use URI::Template;
my $template = URI::Template.new(template => 'http://localhost/endpoint{?foo,bar}');
$client.get($template.process(foo => 1, bar => 'simple text param'));
```

`URI::Template` supports the variable expansion/templating described in [RFC 6570](https://tools.ietf.org/html/rfc6570).

I'd love to see that functionality more seamlessly accessible directly from `Cro`.

**Comment by jnthn** [comment]
Implemented in https://github.com/croservices/cro-http/commit/12bdacdee8, documentation in https://github.com/croservices/cro/commit/76a755dba2.
