### ISSUE TITLE
Uris ending with / result in a 404 or 405

### ISSUE THREAD

**Issue by pvoglhofer** [croservices/cro-http#91]
In the documentation https://cro.services/docs/reference/cro-http-router
it is implied that the following route will work with the slash at the end.

   GET /catalogue/
    get -> 'catalogue' {
        ...
    } 

It seems this is not the case and will result in a 404 instead.
We've observed this in an application without any middleware or redirects.

If you have:

get -> 'catalogue/' {
        ...
    } 

it results in a 405

**Comment by jnthn** [comment]
Thanks; seems there was only one wrong case in the router docs. Fixed in https://github.com/croservices/cro/commit/a30bc26afb.
